Category.create!(name: "あいさつ", body: "あいさつの表現を学びましょう")
Question.create!(title: "你好", body: "正しい日本語訳を選びましょう")
QuestionCategory.create!(question_id: 1, category_id: 1)
Answer.create!(body: "こんにちは", question_id: 1, is_correct: true)
Answer.create!(body: "さようなら", question_id: 1, is_correct: false)
Answer.create!(body: "ありがとう", question_id: 1, is_correct: false)
Answer.create!(body: "ごめんなさい", question_id: 1, is_correct: false)
Question.create!(title: "謝謝", body: "正しい日本語訳を選びましょう")
QuestionCategory.create!(question_id: 2, category_id: 1)
Answer.create!(body: "さようなら", question_id: 2, is_correct: false)
Answer.create!(body: "ごめんなさい", question_id: 2, is_correct: false)
Answer.create!(body: "ありがとう", question_id: 2, is_correct: true)
Answer.create!(body: "こんにちは", question_id: 2, is_correct: false)
